# Site settings
title: nber1994
motto: 地球上没有新鲜事
email: m18710895391@163.com
description: > # this means to ignore newlines until "baseurl:"
    地球是没有新鲜事
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nber1994.github.io" # the base hostname & protocol for your site
twitter_username: nber1994
github_username:  nber1994

# Build settings
markdown: kramdown
